/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./../src/views/components/ActionButton/src/ActionButton.vue')['default']
    ProButton: typeof import('component-library')['ProButton']
    ProCard: typeof import('component-library')['ProCard']
    ProConfigProvider: typeof import('component-library')['ProConfigProvider']
    ProDivider: typeof import('component-library')['ProDivider']
    ProFormDialog: typeof import('component-library')['ProFormDialog']
    ProInput: typeof import('component-library')['ProInput']
    ProInputNumber: typeof import('component-library')['ProInputNumber']
    ProSearchTable: typeof import('component-library')['ProSearchTable']
    ProSearchTableDialog: typeof import('component-library')['ProSearchTableDialog']
    ProSelect: typeof import('component-library')['ProSelect']
    ProText: typeof import('component-library')['ProText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
